resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/bwits/flight-school
    branch: master

jobs:
- name: test-app
  plan:
  - get: flight-school
    trigger: true
    get_params:
      skip_download: true
  - task: tests
    file: flight-school/build.yml
